services:
  # Banco de dados MySQL
  database:
    image: mysql:8.0
    container_name: sql_injection_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vulnerable_app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  # Aplicação web vulnerável
  webapp:
    build: ./webapp
    container_name: vulnerable_webapp
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=vulnerable_app
    networks:
      - app_network

  # Aplicação web segura (mitigações implementadas)
  webapp_secure:
    build: ./webapp
    container_name: secure_webapp
    ports:
      - "5001:5001"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=vulnerable_app
    command: ["python", "app_secure.py"]
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge 